### ISSUE TITLE
[已解决] 无法点击GUI中二维码链接，扫码后无法获得 session.token

### ISSUE THREAD

**Issue by TZFC** [koishijs/novelai-bot#18]
解决方法：
按下文的 尝试解决 与 再次尝试解决 做完后。多次停用再启用 go-cqhttp 和 adapter-onebot
具体原因未知

复现方法：
在 插件市场 中下载 koishi-plugin-novelai 1.5.5
在 依赖管理 中将 @koishijs/plugin-adapter-onebot 更新至 5.2.3
在 依赖管理 中将 koishi-plugin-gocqhttp 更新至 3.1.1
在 插件配置 中配置好 novelai 并启用，在沙盒中确认可以使用
在 插件配置 中配置好 gocqhttp 并停用再启用
在 插件配置 中配置好  adapter-onebot 并启用
点击GUI中的链接进行滑条验证
_在第二部验证中无法点击二维码选项_

尝试解决：
进入 C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\accounts\QQ_ACCOUNT\logs
打开 DATA.txt, 最后一行有二维码链接
把链接复制进浏览器并成功扫码
在 插件配置 将 adapter-onebot 停用再启用
显示 已成功创建 go-cqhttp 子进程。
使用QQ交互没有反应

问题表征：
弹出空白go-cqhttp.exe执行窗口
C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\accounts\QQ_ACCOUNT\logs 不更新
C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\accounts\QQ_ACCOUNT 下缺失session.token

再次尝试解决：
将 QQ_ACCOUNT 目录下的 config.yml 以及 device.json 复制进C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\node_modules\go-cqhttp\bin
通过cmd运行C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\node_modules\go-cqhttp\bin\go-cqhttp.exe，顺利得到 session.token 并在 go-cqhttp.exe 窗口中可以看到qq消息
将 session.token 复制到 QQ_ACCOUNT 目录下， 在 插件配置 将adapter-onebot 停用再启用
显示 已成功创建 go-cqhttp 子进程。
然而使用QQ交互依然没有反应，且log不更新

相关配置文件：
```
# go-cqhttp 默认配置文件
# https://github.com/Mrs4s/go-cqhttp/blob/177ba9d8c2b1d86301f0bf3e0714710fe3c40af4/modules/config/default_config.yml

# 账号相关
account:
  # QQ账号
  uin: 123456
  # 密码为空时使用扫码登录
  password: 'wwwwww'
  # 是否开启密码加密
  encrypt: false
  # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  status: 0

  # 重连设置
  relogin:
    # 首次重连延迟, 单位秒
    delay: 3
    # 重连间隔
    interval: 3
    # 最大重连次数, 0为无限制
    max-times: 0

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true
  # 是否允许发送临时会话消息
  allow-temp-session: false

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string, array
  post-format: string
  <<: {"ignore-invalid-cqcode":true,"force-fragment":false,"fix-url":true,"proxy-rewrite":"","report-self-message":true,"remove-reply-at":true,"extra-reply-data":true,"skip-mime-scan":false}

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用日志颜色
  log-colorful: true
  # 是否启用调试模式
  debug: false

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

# 数据库相关设置
database:
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db

servers:
  # HTTP 通信设置
  # https://github.com/Mrs4s/go-cqhttp/blob/177ba9d8c2b1d86301f0bf3e0714710fe3c40af4/server/http.go#L82
  - http:
      # 是否关闭正向HTTP服务器
      disabled: true
      # HTTP监听地址
      address: 
      # 反向HTTP超时时间, 单位秒
      # 最小值为5，小于5将会忽略本项设置
      timeout: 5
      # 长轮询拓展
      long-polling:
        enabled: false
        # 消息队列大小，0 表示不限制队列大小，谨慎使用
        max-queue-size: 2000
      middlewares:
        <<: *default # 引用默认中间件
      # 反向HTTP POST地址列表
      post:
        - url: http://localhost:5140/onebot
          secret: ''
          # 最大重试，0 时禁用
          # max-retries: 3
          # 重试时间，单位毫秒，0 时立即
          # retries-interval: 1500

  # 正向WS设置
  # https://github.com/Mrs4s/go-cqhttp/blob/177ba9d8c2b1d86301f0bf3e0714710fe3c40af4/server/websocket.go#L79
  - ws:
      # 是否禁用正向WS服务器
      disabled: true
      # 正向WS服务器监听地址
      address: 
      middlewares:
        <<: *default # 引用默认中间件

  # 反向WS设置
  # https://github.com/Mrs4s/go-cqhttp/blob/177ba9d8c2b1d86301f0bf3e0714710fe3c40af4/server/websocket.go#L87
  - ws-reverse:
      # 是否禁用当前反向WS服务
      disabled: false
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://localhost:5140/onebot
      # 反向WS API 地址
      # api: ws://your_websocket_api.server
      # 反向WS Event 地址
      # event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```

koishi.yml
```
host: localhost
port: 5140
maxPort: 5149
plugins:
  group:basic:
    help: null
    ~rate-limit: null
    suggest: null
  group:console:
    console:
      open: true
    ~dataview: null
    logger: null
    insight: null
    market:
      registry:
        endpoint: https://registry.npmmirror.com
      search:
        endpoint: https://registry.koishi.chat/index.json
    sandbox: null
    status: null
  group:adapter:
    adapter-onebot:
      selfId: '123456'
      gocqhttp:
        password: wwwwww
        enabled: true
      protocol: ws-reverse
    ~adapter-discord: null
    ~adapter-telegram: null
    gocqhttp:
      message:
        ignore-invalid-cqcode: true
        fix-url: true
        remove-reply-at: true
        extra-reply-data: true
        report-self-message: true
  ~:un1at3: {}
  novelai:
    token: >-
      MY_TOKEN
    allowAnlas: false
```
